name: ds-lab
channels:
  - conda-forge
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults # This is a conda-forge channel that disables default channels
dependencies:
  - python=3.11.5 # Python interpreter
  - poetry=1.4.0 # Python package manager
platforms:
  - linux-64 # For Linux PCs
  - osx-64 # For Intel Macs
  - osx-arm64  # For Apple Silicon, e.g. M1/M2
  - linux-aarch64  # aka arm64, use for Docker on Apple Silicon
  - linux-ppc64le  # IBM PowerPC
