name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.5'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install conda-lock
      run: |
        conda install --channel=conda-forge --name=base conda-lock
    - name: Create and activate conda environment from the lockfile
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda-lock install --name ds-lab conda-lock.yml
        conda activate ds-lab
        conda env list
        conda env export
        poetry about
    - name: Install project dependencies specified in pyproject.toml
      run: |
        source $CONDA/etc/profile.d/conda.sh
        poetry install
        poetry run pre-commit
    - name: Test with pytest
      run: |
        poetry run pytest
