name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.5'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install conda-lock
      run: |
        conda install --channel=conda-forge --name=base conda-lock
    - name: Create conda environment from the lockfile
      run: |
        conda-lock install --name ds-lab conda-lock.yml
    - name: Initialize conda for shell interaction
      run: |
        conda init --all
    - name: Activate conda environment
      run: |
        conda activate ds-lab
    - name: Install project dependencies specified in pyproject.toml
      run: |
        make dependencies
    - name: Test with pytest
      run: |
        make tests
